version: '3.3'

volumes:
  postgres_data:
  prometheus_data:

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jbpm
      POSTGRES_USER: jbpm
      POSTGRES_PASSWORD: jbpm
    networks:
      - local_net

  jbpm:
    image: jboss/jbpm-server-full
    container_name: jbpm
    environment:
      JBPM_DB_DRIVER: postgres
      JBPM_DB_HOST: postgres
    ports:
      - 8080:8080
      - 8001:8001
    depends_on:
      - postgres
    networks:
      - local_net

  prometheus:
    image: prom/prometheus
    container_name: promt
    user: root
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    container_name: prometheus
    restart: always
    networks:
      - local_net
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    volumes:
      - ./grafana/grafana.ini/:/etc/grafana/grafana.ini
    networks:
      - local_net
    ports:
      - 3000:3000

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - jbpm
      - grafana
      - prometheus
      - node-exporter
    networks:
      - local_net

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - local_net

networks:
  local_net:
    driver: bridge
